'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("InventorySystem.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property glyphicons_137_cogwheel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glyphicons_137_cogwheel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.6.4 http://jquery.com/ | http://jquery.org/license */
        '''(function(a,b){function cu(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cr(a){if(!cg[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ch||(ch=c.createElement(&quot;iframe&quot;),ch.frameBorder=ch.width=ch.height=0),b.appendChild(ch);if(!ci||!ch.createElement)ci=(ch.contentWindow||ch.contentDocument).document,ci.write((c.compatMode===&quot;CSS1Compat&quot;?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_1_6_4_min() As String
            Get
                Return ResourceManager.GetString("jquery_1_6_4_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.8.2 jquery.com | jquery.org/license */
        '''(function(a,b){function G(a){var b=F[a]={};return p.each(a.split(s),function(a,c){b[c]=!0}),b}function J(a,c,d){if(d===b&amp;&amp;a.nodeType===1){var e=&quot;data-&quot;+c.replace(I,&quot;-$1&quot;).toLowerCase();d=a.getAttribute(e);if(typeof d==&quot;string&quot;){try{d=d===&quot;true&quot;?!0:d===&quot;false&quot;?!1:d===&quot;null&quot;?null:+d+&quot;&quot;===d?+d:H.test(d)?p.parseJSON(d):d}catch(f){}p.data(a,c,d)}else d=b}return d}function K(a){var b;for(b in a){if(b===&quot;data&quot;&amp;&amp;p.isEmptyObject(a[b]))continue;if(b!==&quot;toJSON&quot;)ret [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_1_8_2_min() As String
            Get
                Return ResourceManager.GetString("jquery_1_8_2_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        '''* jQuery UI CSS Framework
        '''* Copyright (c) 2010 AUTHORS.txt (http://jqueryui.com/about)
        '''* Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
        '''*/
        '''/* Layout helpers
        '''----------------------------------*/
        '''.ui-helper-hidden { display: none; }
        '''.ui-helper-hidden-accessible { position: absolute; left: -99999999px; }
        '''.ui-helper-reset { margin: 0; padding: 0; border: 0; outline: 0; line-height: 1.3; text-decoration: none; font-size: 100%; list-style: none; }
        '''.ui-helper-clearfi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui() As String
            Get
                Return ResourceManager.GetString("jquery_ui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery UI - v1.8.24 - 2012-09-28
        '''* https://github.com/jquery/jquery-ui
        '''* Includes: jquery.ui.core.js
        '''* Copyright (c) 2012 AUTHORS.txt; Licensed MIT, GPL */
        '''(function(a,b){function c(b,c){var e=b.nodeName.toLowerCase();if(&quot;area&quot;===e){var f=b.parentNode,g=f.name,h;return!b.href||!g||f.nodeName.toLowerCase()!==&quot;map&quot;?!1:(h=a(&quot;img[usemap=#&quot;+g+&quot;]&quot;)[0],!!h&amp;&amp;d(h))}return(/input|select|textarea|button|object/.test(e)?!b.disabled:&quot;a&quot;==e?b.href||c:c)&amp;&amp;d(b)}function d(b){return!a(b).parents().andSelf().filter(funct [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_1_8_24_custom_min() As String
            Get
                Return ResourceManager.GetString("jquery_ui_1_8_24_custom_min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * jQuery UI Autocomplete 1.8.16
        ''' *
        ''' * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * http://docs.jquery.com/UI/Autocomplete
        ''' *
        ''' * Depends:
        ''' *	jquery.ui.core.js
        ''' *	jquery.ui.widget.js
        ''' *	jquery.ui.position.js
        ''' */
        '''(function ($, undefined) {
        '''
        '''    // used to prevent race conditions with remote data sources
        '''    var requestIndex = 0;
        '''
        '''    $.widget(&quot;ui.autocomplete&quot;, {
        '''        options: {
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_autocomplete() As String
            Get
                Return ResourceManager.GetString("jquery_ui_autocomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * jQuery UI Button 1.8.16
        ''' *
        ''' * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * http://docs.jquery.com/UI/Button
        ''' *
        ''' * Depends:
        ''' *	jquery.ui.core.js
        ''' *	jquery.ui.widget.js
        ''' */
        '''(function( $, undefined ) {
        '''
        '''var lastActive, startXPos, startYPos, clickDragged,
        '''	baseClasses = &quot;ui-button ui-widget ui-state-default ui-corner-all&quot;,
        '''	stateClasses = &quot;ui-state-hover ui-state-active &quot;,
        '''	typeClasses = &quot;ui-button-icon [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_button() As String
            Get
                Return ResourceManager.GetString("jquery_ui_button", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * Developer:	Eric Faust
        ''' * Date:		November 25, 2011
        ''' * Description:	Used by the Editable Drop Down List control
        ''' */
        '''// Start jquery combobox
        '''(function ($) {
        '''    $.widget(&quot;ui.combobox&quot;, {
        '''        _create: function () {
        '''            var self = this,
        '''					select = this.element.hide(),
        '''					selected = select.children(&quot;:selected&quot;),
        '''					value = select.val() ? select.val() : selected.val() ? selected.text() : &quot;&quot;;
        '''            var input = this.input = $(&quot;&lt;input&gt;&quot;)
        '''					.insertAfter(select)
        '''					.v [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_combobox() As String
            Get
                Return ResourceManager.GetString("jquery_ui_combobox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * jQuery UI 1.8.16
        ''' *
        ''' * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * http://docs.jquery.com/UI
        ''' */
        '''(function( $, undefined ) {
        '''
        '''// prevent duplicate loading
        '''// this is only a problem because we proxy existing functions
        '''// and we don&apos;t want to double proxy them
        '''$.ui = $.ui || {};
        '''if ( $.ui.version ) {
        '''	return;
        '''}
        '''
        '''$.extend( $.ui, {
        '''	version: &quot;1.8.16&quot;,
        '''
        '''	keyCode: {
        '''		ALT: 18,
        '''		BACKSPACE: 8,
        '''		CAPS_LOC [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_core() As String
            Get
                Return ResourceManager.GetString("jquery_ui_core", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*
        ''' * jQuery UI Position 1.8.16
        ''' *
        ''' * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * http://docs.jquery.com/UI/Position
        ''' */
        '''(function( $, undefined ) {
        '''
        '''$.ui = $.ui || {};
        '''
        '''var horizontalPositions = /left|center|right/,
        '''	verticalPositions = /top|center|bottom/,
        '''	center = &quot;center&quot;,
        '''	_position = $.fn.position,
        '''	_offset = $.fn.offset;
        '''
        '''$.fn.position = function( options ) {
        '''	if ( !options || !options.of ) {
        '''		r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_position() As String
            Get
                Return ResourceManager.GetString("jquery_ui_position", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * jQuery UI Widget 1.8.16
        ''' *
        ''' * Copyright 2011, AUTHORS.txt (http://jqueryui.com/about)
        ''' * Dual licensed under the MIT or GPL Version 2 licenses.
        ''' * http://jquery.org/license
        ''' *
        ''' * http://docs.jquery.com/UI/Widget
        ''' */
        '''(function( $, undefined ) {
        '''
        '''// jQuery 1.4+
        '''if ( $.cleanData ) {
        '''	var _cleanData = $.cleanData;
        '''	$.cleanData = function( elems ) {
        '''		for ( var i = 0, elem; (elem = elems[i]) != null; i++ ) {
        '''			try {
        '''				$( elem ).triggerHandler( &quot;remove&quot; );
        '''			// http://bugs.jquery.com/ticket/8235
        '''			} c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jquery_ui_widget() As String
            Get
                Return ResourceManager.GetString("jquery_ui_widget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        '''xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        '''xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        '''xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        '''xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        '''
        '''&lt;head&gt;
        '''&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        '''&lt;meta name=ProgId content=Word.Document&gt;
        '''&lt;meta name=Generator content=&quot;Microsoft Word 15&quot;&gt;
        '''&lt;meta name=Originator content=&quot;Microsoft Word 15&quot;&gt;
        '''&lt;link rel=File-List href=&quot;NewEquip [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property NewEquipment() As String
            Get
                Return ResourceManager.GetString("NewEquipment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_diagonals_thick_18_b81900_40x40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_diagonals_thick_18_b81900_40x40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_diagonals_thick_20_666666_40x40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_diagonals_thick_20_666666_40x40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_flat_0_aaaaaa_40x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_flat_0_aaaaaa_40x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_flat_10_000000_40x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_flat_10_000000_40x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_flat_75_ffffff_40x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_flat_75_ffffff_40x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_glass_100_f6f6f6_1x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_glass_100_f6f6f6_1x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_glass_100_fdf5ce_1x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_glass_100_fdf5ce_1x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_glass_65_ffffff_1x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_glass_65_ffffff_1x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_glass_75_dadada_1x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_glass_75_dadada_1x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_glass_75_e6e6e6_1x400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_glass_75_e6e6e6_1x400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_gloss_wave_35_f6a828_500x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_gloss_wave_35_f6a828_500x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_highlight_soft_100_eeeeee_1x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_highlight_soft_100_eeeeee_1x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_bg_highlight_soft_75_ffe45c_1x100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_bg_highlight_soft_75_ffe45c_1x100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_222222_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_222222_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_228ef1_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_228ef1_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_454545_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_454545_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_888888_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_888888_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_ef8c08_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_ef8c08_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_ffd27a_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_ffd27a_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ui_icons_ffffff_256x240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ui_icons_ffffff_256x240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
